### ISSUE TITLE
Make Kanban board elements draggable to allow moving between different status types

### ISSUE THREAD

**Issue by RuthwikHM** [asvch/jobtracker#3]
**Is your feature request related to a problem? Please describe.**
Frustrated when I have to go back to the new application view to edit existing application's status.

**Describe the solution you'd like**
I would like a bunch of columns listing the various types of application status available. Each application I have logged should be allowed to move between these columns by dragging and dropping them in the relevant section.

**Describe alternatives you've considered**
Allowing edits from this page itself but the drag and drop feature seems more intuitive.

**Additional context**
None

**Comment by asvch** [comment]
Works!
![image](https://github.com/user-attachments/assets/10bf66ff-d281-4aa6-a327-a1e42c4004f7)
